# Generated by Django 3.2.5 on 2021-08-03 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=120)),
                ('Professional_Status', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('How_you_came_to_know_about_us', models.CharField(max_length=250)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=3, null=True)),
                ('Mobile_Number', models.CharField(max_length=10, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=150, null=True)),
                ('Introduction', models.TextField(null=True)),
                ('Currently_or_was_working_for', models.CharField(blank=True, max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('First_Experience', models.CharField(blank=True, max_length=250)),
                ('First_Experience_Description', models.TextField(blank=True)),
                ('Second_Experience', models.CharField(blank=True, max_length=250)),
                ('Second_Experience_Description', models.TextField(blank=True)),
                ('Third_Experience', models.CharField(blank=True, max_length=250)),
                ('Third_Experience_Description', models.TextField(blank=True)),
                ('Fourth_Experience', models.CharField(blank=True, max_length=250)),
                ('Fourth_Experience_Description', models.TextField(blank=True)),
                ('Fifth_Experience', models.CharField(blank=True, max_length=250)),
                ('Fifth_Experience_Description', models.TextField(blank=True)),
                ('School', models.CharField(max_length=250, null=True)),
                ('School_Description', models.TextField(null=True)),
                ('College', models.CharField(max_length=250, null=True)),
                ('College_Description', models.TextField(null=True)),
                ('First_Skill', models.CharField(max_length=50, null=True)),
                ('Second_Skill', models.CharField(max_length=50, null=True)),
                ('Third_Skill', models.CharField(max_length=50, null=True)),
                ('Fourth_Skill', models.CharField(blank=True, max_length=50)),
                ('Fifth_Skill', models.CharField(blank=True, max_length=50)),
                ('Sixth_Skill', models.CharField(blank=True, max_length=50)),
                ('Seventh_Skill', models.CharField(blank=True, max_length=50)),
                ('Fist_Language', models.CharField(max_length=100, null=True)),
                ('Second_Language', models.CharField(blank=True, max_length=100)),
                ('Third_Language', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
