# Generated by Django 3.2.5 on 2021-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=120)),
                ('Professional_Status', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('How_you_came_to_know_about_us', models.CharField(max_length=250)),
                ('Message', models.TextField()),
            ],
        ),
    ]
