# Generated by Django 3.2.5 on 2021-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='Age',
        ),
        migrations.AddField(
            model_name='professional',
            name='Date_of_Birth',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
