# Generated by Django 3.2.5 on 2021-08-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210809_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='Fifth_Skill',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='professional',
            name='First_Skill',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Fist_Language',
            field=models.CharField(max_length=112, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Fourth_Skill',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Second_Language',
            field=models.CharField(blank=True, max_length=112),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Second_Skill',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Seventh_Skill',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Sixth_Skill',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Third_Language',
            field=models.CharField(blank=True, max_length=112),
        ),
        migrations.AlterField(
            model_name='professional',
            name='Third_Skill',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
