# Generated by Django 3.2.5 on 2021-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_professional_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
