# Generated by Django 3.2.5 on 2021-08-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210815_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='Fifth_Experience_Company_Duration',
            new_name='Fifth_Exp_Company_Duration',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Fifth_Experience_Company_Location',
            new_name='Fifth_Exp_Company_Location',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Fifth_Experience_Company_Name',
            new_name='Fifth_Exp_Company_Name',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='First_Experience_Company_Duration',
            new_name='First_Exp_Company_Duration',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='First_Experience_Company_Location',
            new_name='First_Exp_Company_Location',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='First_Experience_Company_Name',
            new_name='First_Exp_Company_Name',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Fist_Language',
            new_name='First_Language',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Fourth_Experience_Company_Duration',
            new_name='Fourth_Exp_Company_Duration',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Fourth_Experience_Company_Location',
            new_name='Fourth_Exp_Company_Location',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Fourth_Experience_Company_Name',
            new_name='Fourth_Exp_Company_Name',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Second_Experience_Company_Duration',
            new_name='Second_Exp_Company_Duration',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Second_Experience_Company_Location',
            new_name='Second_Exp_Company_Location',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Second_Experience_Company_Name',
            new_name='Second_Exp_Company_Name',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Third_Experience_Company_Duration',
            new_name='Third_Exp_Company_Duration',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Third_Experience_Company_Location',
            new_name='Third_Exp_Company_Location',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='Third_Experience_Company_Name',
            new_name='Third_Exp_Company_Name',
        ),
    ]
