# Generated by Django 3.2.5 on 2021-08-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210815_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='Fist_Language',
            new_name='First_Language',
        ),
    ]
