# Generated by Django 3.2.5 on 2021-08-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210815_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='First_Exp_Company_Duration',
            new_name='First_Company_Duration',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='First_Exp_Company_Location',
            new_name='First_Company_Location',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='First_Exp_Company_Name',
            new_name='First_Company_Name',
        ),
    ]
