# Generated by Django 3.2.5 on 2021-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210815_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='Email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
